### ISSUE TITLE
little suggest

### ISSUE THREAD

**Issue by BaiFeng666** [86hrs/cheat-menu#1]
old version i can compile but new version i can't compile... dont know why

Flow:
can change the color of your enemies based on their health
Blood volume is high to low like  Green -> Yello -> Red

Ignore flash:
store offsets::m_flFlashMaxAlpha before write this 0,  after closing the option ,restore its value

**Comment by 86hrs** [comment]
Thank you for the recommendation, maybe u can help find the max value of the flash alpha, and I think you can't compile because of the icon I added or the font, try removing those, thx much appreciated

**Comment by 86hrs** [comment]
Thank you for the recommendations, I will repair the ignore flash option and I will try to implement flow, maybe u can't compile bc of the font or icon I added, thank you for the help

**Comment by 86hrs** [comment]
I am also new, I try to make it simple
