### ISSUE TITLE
Fov mistake

### ISSUE THREAD

**Issue by BaiFeng666** [86hrs/cheat-menu#3]
`
if (globals::fov)
			mem.Write(localPlayer + offsets::m_iFOV, globals::fovValue);
		else
			mem.Write(localPlayer + offsets::m_iFOV, 90);
`

Forced Angle change when sniper gun opens

Perhaps there is an offsets that tell if the player has turned on the scope？

**Comment by 86hrs** [comment]
Yes, this is the offset `constexpr ::std::ptrdiff_t m_bIsScoped = 0x9974;` but I have yet to fint the solution, could u make a pull request is u find it?

**Comment by BaiFeng666** [comment]
this is easy code for fix Fov

`// ----------Fov----------
		if (globals::fov)
			if (!mem.Read<bool>(localPlayer + offsets::m_bIsScoped))
				mem.Write(localPlayer + offsets::m_iFOV, globals::fovValue);
		else
			if (!mem.Read<bool>(localPlayer + offsets::m_bIsScoped))
				mem.Write(localPlayer + offsets::m_iFOV, mem.Read<int32_t>(localPlayer + offsets::m_iDefaultFOV));
		// ----------Remove Recoil----------`


and ignore flash there is also a crude fix
There is a problem with the existing code, which is still ignore flash when the option is turned on and then turned off
`
		if (globals::ignoreFlash)
			mem.Write(localPlayer + offsets::m_flFlashMaxAlpha, 0.f);
		else
			mem.Write(localPlayer + offsets::m_flFlashMaxAlpha, 255.f);`



i cant pull request because i cant compile...and i not good at github

**Comment by BaiFeng666** [comment]
![image](https://user-images.githubusercontent.com/69395668/230527794-b1e214ef-94f7-4774-899a-379196e4ae37.png)

**Comment by BaiFeng666** [comment]
![image](https://user-images.githubusercontent.com/69395668/230527838-0a3ecf85-3319-4a18-a96a-bda19ddf0b53.png)

**Comment by 86hrs** [comment]
Thanks for the fov I will implement at home, but for flash just use different offset

**Comment by 86hrs** [comment]
![image](https://user-images.githubusercontent.com/129086894/230553129-f1ea20c3-2b78-41a0-876f-c846268a273a.jpeg)

**Comment by BaiFeng666** [comment]
> ![image](https://user-images.githubusercontent.com/129086894/230553129-f1ea20c3-2b78-41a0-876f-c846268a273a.jpeg)

nice ,Using this offset is convenient
